version: '3'

services:
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - "MYSQL_CONNECTION_STRING=Server=db;Port=3306;Database=todo;Uid=root;Pwd=mypassword;"
  
  db:
    image: mysql:5.7.25
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=todo"
      - "MYSQL_ROOT_PASSWORD=mypassword"
  
volumes:
  
  dbdata: