version: '3'

services:
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - "POSTGRES_CONNECTION_STRING=Host=db;Port=5432;Database=todo;Username=admin;Password=mypassword;"
  
  db:
    image: postgres:12.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=mypassword"
      - "POSTGRES_DB=todo"
  
volumes:
  
  dbdata: